name: Build and Push docker image
on: workflow_dispatch

jobs:
  image:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker repository
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          ecr: false
      -
        name: Build and Push Dynamo
        uses: docker/build-push-action@v6
        with:
          file: dynamo.Dockerfile
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_TAG }}-dynamo:latest
      -
        name: Build and Push Sync
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_TAG }}-sync:latest
